[workspace]
resolver = "2"
members = [
  "crates/tdln-permit",
  "crates/tdln-certified-runtime",
  "crates/tdln-runtime-wasm",
  "crates/tdln-runner",
  "wrappers/*/domain",
  "wrappers/*/service"
]
exclude = ["crates/wrapper-template"]

[workspace.package]
edition = "2021"
license = "Apache-2.0 OR MIT"

[workspace.metadata.ci]
rust_channel = "stable"
